# -*- coding: utf-8 -*-
"""Md. Fuad Haider Dipu_Final Term.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0RvPqlHaPfKLARt3l04l_JB8DcxyRGN

**Email Address: dipuhaider@gmail.com**

**Answer to the Q1**
"""

import numpy as np
import pandas as pd

df = pd.read_csv("final-employee-ds.csv")
# df

training_hour_arr = df['TrainingHours'].to_numpy(dtype=float)
mean = float(np.nanmean(training_hour_arr))
std = float(np.nanstd(training_hour_arr))

# print(training_hour_arr)
print(mean)
print(std)

"""**Answer to the Q2**"""

import pandas as pd

df = pd.read_csv("final-employee-ds.csv")

df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

dept_median = df.groupby('Department')['Salary'].transform('median')
df['Salary'] = df['Salary'].fillna(dept_median)

calclulate_condition = (df['ExperienceYears'] > 12) & (df['ProjectCount'] > 5)
total_salary_sum = float(df.loc[calclulate_condition, 'Salary'].sum())
print(total_salary_sum)

"""**Answer to the Q3**"""

import pandas as pd

df = pd.read_csv("final-employee-ds.csv")

employees_filter = ((df['Department'].isin(['IT', 'Finance'])) & (df['Age'].between(30, 45)) & (df['PerformanceScore'] > 88))

table = df.loc[employees_filter, ['Name', 'Department', 'Salary', 'PerformanceScore']].copy()
table = table.sort_values('Salary', ascending=False).reset_index(drop=True)

print(table.to_string(index=False))

"""**Answer to the Q4**"""

import numpy as np
import pandas as pd

df = pd.read_csv("final-employee-ds.csv")

df['WorkHoursPerWeek'] = pd.to_numeric(df['WorkHoursPerWeek'])

salary_per_hour = df['WorkHoursPerWeek'] * 4
df['SalaryPerHour'] = np.where(salary_per_hour > 0, df['Salary'] / salary_per_hour, np.nan)

table = df[['Name', 'SalaryPerHour']].nlargest(5, 'SalaryPerHour').reset_index(drop=True)

print(table)

"""**Answer to the Q5**"""

import matplotlib.pyplot as plt

counts = df.groupby(['Department', 'Gender']).size().unstack(fill_value=0)

fig, ax = plt.subplots(figsize=(9,5))
counts.plot(kind='bar', stacked=True, ax=ax, edgecolor='black')
ax.set_xlabel('Department')
ax.set_ylabel('Number of employees')
ax.set_title('Count of Employees by Department and Gender')
ax.legend(title='Gender')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

plt.show()