# -*- coding: utf-8 -*-
"""Md. Fuad Haider Dipu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hn0rvxen2j1wZG181qru2RszitxL78ke

**Email Address: dipuhaider@gmail.com**
"""

# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")

"""Answer to the **Q1**"""

import numpy as np
import pandas as pd

df = pd.read_csv("employees.csv")

ages = df["age"].to_numpy()
salaries = df["salary"].to_numpy()

print(ages)
print(salaries)

print(ages.dtype)
print(ages.ndim)
print(ages.shape)
print(ages.size)

print(salaries.dtype)
print(salaries.ndim)
print(salaries.shape)
print(salaries.size)

"""**Answer to the Q2**"""

highest_sal = np.max(salaries)
lowest_sal = np.min(salaries)
avg_sal = np.mean(salaries)
avg_age = np.mean(ages)

print(highest_sal)
print(lowest_sal)
print(avg_sal)
print(avg_age)

"""**Answer to the Q3**"""

age_over_30 = ages[ages>30]
count_over_30 = age_over_30.size

print(age_over_30)
print(count_over_30)

"""**Answer to the Q4**"""

age_increase_by_5 = ages + 5

print(age_increase_by_5)

"""**Answer to the Q5**"""

total_salary = np.sum(salaries)
diff_salary = np.max(salaries) - np.min(salaries)

print(total_salary)
print(diff_salary)

"""**Answer to the Q6**"""

print(df.head(5))
print(df.info())
print(df.describe(include="all"))

"""**Answer to the Q7**"""

specific = df[["id", "age", "salary"]]

print(specific.tail(3))

"""**Answer to the Q8**"""

it_dept = df.loc[df["dept"] == "IT"]

print(it_dept)
print(it_dept.shape[0])

"""**Answer to the Q9**"""

top_3_emp = df.sort_values(by="salary", ascending=False).loc[:, ["id", "salary", "dept", "age"]].head(3)
print(top_3_emp)

"""**Answer to the Q10**"""

salary_value= df.copy()
salary_value.loc[salary_value["salary"] > 80000, "salary"] = 80000

print(salary_value[["id", "salary"]])

new_avg_salary = salary_value["salary"].mean()
print(new_avg_salary)